version: '3.4'

services:
  app:
    image: ${DOCKER_REGISTRY-}app
    environment:
      ConnectionStrings__postgres: "Server=db;Port=5432;Database=PostBot;User Id=postgres;Password=the_password"
      Telegram__BotToken: "7436167284:AAHcdqBQxnRVLZscHLfxS7EaHMX3vZXmER4"
      BaseUrl: "https://poster.xwaifu.app"
      ASPNETCORE_URLS: "http://+:8080"
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: app/Dockerfile
    depends_on:
      - db
    volumes:
      - ./results:/app/telegram/similar

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: PostBot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: the_password
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
