version: '3.8'

services:
  telegram-analyzer:
    build: .
    container_name: telegram-analyzer
    volumes:
      - ./sessionsPREM:/app/sessionsPREM
      - ./similar:/app/similar
    ports:
      - "8000:8000"
    networks:
      - analyzer-network
    environment:
      - PYTHONUNBUFFERED=1

  zakup-api:
    build:
      context: ./Zakup.WebHost
      dockerfile: Dockerfile
    container_name: zakup-api
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - analyzer-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;https://+:8081

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - analyzer-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  analyzer-network:
    driver: bridge

volumes:
  minio_data: 