namespace Zakup.Common.Enums;

//Нужно для передачи типа callback в данные callback с минимальной длиной строки
public enum CallbackType
{
    PDPApprove,
    Unknown,
    RateChannel,
    ZakupCreate,
    MyChannelsList,
    GoogleSheets,
    AdminPanel,
    Help,
    NewChannel,
    ConfirmChannelAlias,
    FirstAdPost,
    ShowChannelMenu,
    AdPostsList,
    ChannelStatistic,
    ChannelAutoApprove,
    ChangeCannelLabel,
    AddChannelAdmin,
    ApproveAllChannelRequest,
    AddChannelChat,
    DeleteChannel,
    AdPostMenu,
    CreatePost,
    AddPostButton,
    GenerateAdPost,
    DeleteAdPost,
    EnableAutoApprove,
    DisableAutoApprove,
    AdminInfo,
    AddNewChannelAdmin,
    RemoveAdmin,
    HelpQuestion,
    HelpAnOffer,
    ChooseZakupDate,
    DeleteZakup,
    AddZakupPrice,
    ZakupChannelPrivate,
    ZakupLinkType,
    DeleteChannelComplete,
    ZakupStatistic,
    CheckSubscribers,
    ShowMembers,
    ChangeZakupPrice
}